FROM node:12.18.1-slim
#RUN adduser --disabled-password karanth
#USER karanth
WORKDIR /code
COPY package*.json ./ 
RUN npm install 
COPY . .
RUN chmod -R 777 /code
EXPOSE 3000
CMD ["npm","start"]


#FROM redhat/ubi9
#WORKDIR /code
#RUN chmod -R 777 /code
#COPY package*.json ./
#RUN yum install -y nodejs 
#RUN npm install
#COPY . .
#RUN chmod -R 777 /code
#EXPOSE 3000
#CMD ["npm","start"]

# Stage 1 - Build
#FROM node:12.18.1-alpine as build
# WORKDIR /code
# COPY package*.json ./
# RUN npm install --no-cache
# COPY . .

# Stage 2 - Run
# FROM node:12.18.1-alpine
# WORKDIR /code
# COPY --from=build /code .
# RUN chmod -R 777 /code
# EXPOSE 3000
# CMD ["npm","start"]
